### ISSUE TITLE
Dodajanje tabel "tip" in "oblika"

### ISSUE THREAD

**Issue by m11rtin** [m11rtin/patroni#4]
V SQL bazi bi morali biti še dve tabeli, saj se atributa tip in oblika večkrat ponovita itd.

**Comment by drobilc** [comment]
Sem že popravil, objavim jutri :)

**Comment by m11rtin** [comment]
Sem popravil sam.

**Comment by drobilc** [comment]
Ponavadi je smotrno popravek tudi objaviti...

**Comment by m11rtin** [comment]
Se strinjam. To sem v nasprotju s tabo tudi naredil.
